### ISSUE TITLE
Error when having the "lovelace-hue-like-light-card" and the entities from "lovelace-auto-entities"  in a grid 

### ISSUE THREAD

**Issue by twanjaarsveld** [Gh61/lovelace-hue-like-light-card#103]
Here is the code i used 
the "lovelace-auto-entities" work in a grid if i use a other card 

```yaml
square: false
type: grid
columns: 1
cards:
  - type: custom:auto-entities
    filter:
      include:
        - domain: light
          area: 829d23948f6844f0a15e2a14e4318e23
      exclude:
        - state: unavailable
    card:
      type: custom:hue-like-light-card
      title: Woonkamer
      icon: mdi:sofa
      slider: mushroom
      theme: synthwave
      style: |
        .brightness-slider {
          --mush-control-height: 20px;
          --slider-color: white;
        }
```
