### ISSUE TITLE
Feature Request: Default "On Scene"

### ISSUE THREAD

**Issue by danejur** [Gh61/lovelace-hue-like-light-card#112]
Love this add-on and all of the improvements that you've made to it! One handy thing I would love is for toggling a card's switch to the on position to always set a specific scene. I have a few physical switches that I have configured to always turn on to max brightness regardless of what the lights were set to before they were turned off. I'd love to replicate this functionality with the hue-like card! I imagine it word work something like this:

1. User sets lights to a custom scene, brightness, color, etc.
2. User turns off lights
3. User turns lights back on via hue-like card on switch, which sets the light to the predefined "default state" instead of the previous state.

If this is already in the card and I'm not seeing it in the configuration, I apologize! I might try to poke around the JS myself if I get some time, but I figured I'd log this request regardless.

**Comment by Gh61** [comment]
You can already achieve similar behaviour with this settings:

```yaml
type: custom:hue-like-light-card
entities:
  - light.some_light1
  - light.some_light2
offClickAction: scene
offClickData:
  scene: scene.some_lights_bright
```

With this setting if you click the card (not the switch) when all lights are off, it will activate the `some_lights_bright` scene.

It probably isn't exactly what you wanted (the switch will still be working the same), but maybe it can fit your needs?
