### ISSUE TITLE
Be able to define both entity (zone) and entities (lights for multicolor view)

### ISSUE THREAD

**Issue by finder39** [Gh61/lovelace-hue-like-light-card#24]
If both are defined at once, auto generate scenes from the entity (when valid to) but use the color of the lights in the entities field to color the background of the card

**Comment by Gh61** [comment]
Hi,

thank you for suggestion.
So maybe add some config option (for example `zone[s]`), where you can define rooms and/or zones, from where scenes should be automatically loaded.

**Comment by finder39** [comment]
So currently I use this like this, with `light.bedroom_and_connected` being a zone or room in the Hue app:

```yaml
    - type: entities
      entities:
      - type: custom:hue-like-light-card
        entity: light.bedroom_and_connected
        offClickAction: hue-screen
        showSwitch: false
      - type: custom:hue-like-light-card
        entity: light.upstairs
        offClickAction: hue-screen
        showSwitch: false
      - type: custom:hue-like-light-card
        entity: light.downstairs
        offClickAction: hue-screen
        showSwitch: false
```

That light (which is really a zone or room in the hue app) looks like the following:
<img width="1798" alt="image" src="https://user-images.githubusercontent.com/518673/235741208-4a8d3f2a-72e0-4934-822f-fba8b96459a8.png">


The "lights" attribute would be great to pull from and establish that multicolor design from, but there isn't a direct correlation to HA entities from the hue lights, so being able to pass in an array of the light entities that we do want to base it on would work well.
