### ISSUE TITLE
In a scene where certain lights are turned off, moving the brightness slider turns those lights on even when sliding the brightness down

### ISSUE THREAD

**Issue by recklessnl** [Gh61/lovelace-hue-like-light-card#261]
This is also a very annoying bug in Home Assistant itself - imagine a room with ceiling lights and a desk lamp. In one scene, all the ceiling lights are off, but the desk lamp is on. When I activate the scene through Hass or the lovelace-hue-like-light-card, it works perfectly.

However, when I then want to change the brightness using the slider, it will turn all the ceiling fans on, to that brightness. This is really annoying because it's not how Hue works in the app, where it will only affect the brightness of the lights that are currently on (in this case, the desk lamp). This is the functionality I want.

Is this possible at all?

**Comment by transce080** [comment]
I agree 100%.  In order to be a hue-like control, it needs to work the way the original sliders work.  To restate what @recklessnl said in more formal terms:  

- If the slider control is activated on a group
- When every light in the group is set to on or off
- Then all the lights will be set to the slider value

- If the slider control is activated on a group
- When at least one light is not set to on
- Then only the lights which are already on will be set to the slider value

**Comment by vipzzzzzz** [comment]
This! Drove myself crazy trying to figure out what I was doing wrong... 

I have an area called 'living area' which includes the lights in the master bedroom. When dimming that area the lights in the master bedroom are turned back on when they were turned off, which is really annoying when one of us goes to bed early and the other just wants to hang out a bit longer in one of the other living area's. 

This works fine when using a homekit dashboard, but since i've switched all my dashboards in the home to HA, with this (amazing) card to control lights/scenes the behaviour is different and I haven't been able to figure out a solution.

**Comment by transce080** [comment]
@vipzzzzzz I don't think there is a solution except to fix the logic in the code.  I don't know the specifics yet but making the required change should not be terribly difficult.  As a developer, I should be able to make the changes myself, however I have limited time available so I would like to hear @Gh61 's opinion before starting any work to make sure it's something he would accept a PR for.

**Comment by dsellers1** [comment]
I just wanted to chime in here right quick. Like everyone has already mentioned, this is a limitation of HA itself. A year or two ago I was trying to make a work-around and what I came up with was a "dynamic light group." It was kind of a PITA to set up, but IIRC I pretty much had it working... for one group. It is roughly 100 lines long but the key for each section was this template: 
```yaml
{% set lights = states.light
  | rejectattr('entity_id', 'eq', this.entity_id)
  | rejectattr ('entity_id', 'in', integration_entities('group'))
  | rejectattr ('entity_id', 'in', integration_entities('fullykiosk'))
  | selectattr('state' , 'eq' , 'on')
  | map(attribute='entity_id')
  | list
%}
{{ lights | count > 0 }}
```
In regards to setting the brightness, this is what I used:
```yaml
level_template: >
  {% set lights = states.light
    | rejectattr('entity_id', 'eq', this.entity_id)
    | rejectattr ('entity_id', 'in', integration_entities('group'))
    | rejectattr ('entity_id', 'in', integration_entities('fullykiosk'))
    | selectattr('state' , 'eq' , 'on')
    | map(attribute='entity_id')
    | list
  %}
  {% set bright = lights | map('state_attr', 'brightness') | map('default', 255, true) | list %}
  {{ bright | average | round(0) | int if bright else 0 }}
```
and
```yaml
set_level:
  - variables:
      lights: > 
        {{ states.light
            | rejectattr('entity_id', 'eq', this.entity_id)
            | rejectattr ('entity_id', 'in', integration_entities('group'))
            | rejectattr ('entity_id', 'in', integration_entities('fullykiosk'))
            | selectattr('state' , 'eq' , 'on')
            | selectattr('attributes.brightness', 'defined')
            | map(attribute='entity_id')
            | list
        }}
  - if: "{{ lights | count > 0 }}"
    then:
      - service: light.turn_on
        data:
          entity_id: "{{ lights }}"
          brightness: "{{ brightness }}"
```
I'm not sure if this is helpful or not. One thing I want to mention is this group was designed to handle *all* of the lights in my apartment. It wasn't designed to handle a group or area. Once I realized that was going to be the next step, I pretty much stopped working on it. The workaround turned into dashboard design where pop-ups would let me dim specific lights.
