### ISSUE TITLE
Changing title and icon size, color (styling)

### ISSUE THREAD

**Issue by malkie-hass** [Gh61/lovelace-hue-like-light-card#28]
Hi,
I really like your card and started using it heavily since the last update as it has all features I need now. Was wondering if there is a possibility to get the following things implemented 

- change icon size
- Change title/name font size
- Hide title/name
- Change icon color when turned off. Would love to have it darker when turned off

thank you very much for the great work

Malkie

**Comment by Gh61** [comment]
Hi,

all the things you want are possible with [card-mod](https://github.com/thomasloven/lovelace-card-mod) and settings some custom styles for the card.

```xaml
type: custom:hue-like-light-card
entity: light.study
style: |
  /* Smaller icon */
  ha-card ha-icon {
    transform: scale(1.4);
  }

  /* Smaller title size */
  ha-card h2 {
    font-size: 10px;
  }

  /* Hide the text completely */
  ha-card h2 {
    display:none;
  }

  /* Color of icon, when lights are off */
  ha-card.state-off ha-icon {
    color:red;
  }
```

As you are not the first who wants the icon size to change (I suppose make it smaller?), I might make some setting to set the icon to smaller size (more true to the original).

**Comment by malkie-hass** [comment]
Hey,
wow, i was not aware. Thanks for explaining. Will test that. 
Yes, I wanted to shrink the icon a bit as they are quite big

malkie

**Comment by Percherie** [comment]
Thanks for the tip, I've just reduced the size of the icon. It's much nicer

**Comment by Gh61** [comment]
I think this issue is already resolved. Also in the current [Release](https://github.com/Gh61/lovelace-hue-like-light-card/releases/tag/v1.4.2) the possibility to change icon size (and smaller default icon) has been added.

**Comment by paulbuechner** [comment]
> Hi,
> 
> all the things you want are possible with [card-mod](https://github.com/thomasloven/lovelace-card-mod) and settings some custom styles for the card.
> 
> ```
> type: custom:hue-like-light-card
> entity: light.study
> style: |
>   /* Smaller icon */
>   ha-card ha-icon {
>     transform: scale(1.4);
>   }
> 
>   /* Smaller title size */
>   ha-card h2 {
>     font-size: 10px;
>   }
> 
>   /* Hide the text completely */
>   ha-card h2 {
>     display:none;
>   }
> 
>   /* Color of icon, when lights are off */
>   ha-card.state-off ha-icon {
>     color:red;
>   }
> ```
> 
> As you are not the first who wants the icon size to change (I suppose make it smaller?), I might make some setting to set the icon to smaller size (more true to the original).

Hello! Thank you very much for your effort to bring this card to life!

I have a problem styling the card's elements according to this example...

When having the custom styles applied, no changes seem to take effect. Why could this be...?

```yaml
- type: custom:hue-like-light-card
        title: Ceiling Lamp
        entities:
          - light.living_room_window
          - light.living_room_window_mid
          - light.living_room_base
          - light.living_room_door_mid
          - light.living_room_door
        slider: default # none | mushroom
        showSwitch: false
        offColor: theme-color
        hueScreenBgColor: theme-color
        offShadow: false
        hueBorders: false
        offClickAction: turn-on
        onClickAction: turn-off
        offHoldAction: hue-screen
        onHoldAction: hue-screen
        scenes:
          - entity: scene.living_room_rolling_hills
            # color: rgb(168, 25, 255)
            title: Rolling Hills
            activation: hue.activate_scene
            activationData:
              dynamic: false
              brightness: 180
              # speed: 40
        style: |
          /* Smaller icon */
          ha-card ha-icon {
            transform: scale(1.4);
          }

          /* Smaller title size */
          ha-card h2 {
            font-weight: 700;
            font-size: 10px;
          }

          /* Color of icon, when lights are off */
          ha-card.state-off ha-icon {
            color: red;
          }
```
<img width="726" alt="grafik" src="https://github.com/Gh61/lovelace-hue-like-light-card/assets/45827409/15c573af-6738-4cf0-9ed2-2b8015ac38fe">
