### ISSUE TITLE
Generate light groups from rooms

### ISSUE THREAD

**Issue by GRX** [Gh61/lovelace-hue-like-light-card#30]
Hi,

I love this custom card, with this card I can nearly replicate the Hue app.

But the issue that I have is that my groups are not showing the correct "children".
I'm using a combination of `custom:auto-entities` and `custom:hue-like-light-card`.

Currently my yaml looks like:
```
- type: custom:auto-entities
  card:
    type: entities
    title: Kamers
  filter:
    include:
      - domain: light
        attributes:
          hue_type: "room"
        options:
          type: custom:hue-like-light-card
          offShadow: false
          allowZero: true
          offColor: '#424340'
    exclude:
      - state: unavailable       
```
         
Now this does properly show the different rooms:
![image](https://github.com/Gh61/lovelace-hue-like-light-card/assets/14363136/b43de695-e559-4ed5-9ad8-71b451531955)

But when I select one of the rooms, the only light in the room is the room itself:
_(The room **Achtertuin** has 5 different lights in it)_
![image](https://github.com/Gh61/lovelace-hue-like-light-card/assets/14363136/343565ea-0df8-4fd0-96b7-1c1de26d6618)

---

1. How can I setup the lights so that the corresponding "children" are in each room without manually having to add every single room and light that I have?

2. How can I make sure the corresponding icons are shown?

3. Is there a method to style the shadowroot elements in `ha-switch`/`ha-slider` ( from the styling in the `.js` file?

Thank you for your time, and also for this amazing card!
