### ISSUE TITLE
[Feature Request] Spawn Group member under `Lights` to facilite large group settings

### ISSUE THREAD

**Issue by maxi1134** [Gh61/lovelace-hue-like-light-card#361]
```

    type: custom:hue-like-light-card
    entities:
      - light.group_salon_lights
    groupEntity: light.group_salon_lights
    title: Server
    slider: mushroom
    icon: mdi:server
    

```

Will show 

![Image](https://github.com/user-attachments/assets/f6ddd21a-098c-4364-9af0-75920d4c0750)

Instead of the 10 lights under the `Salon Lights` group; Ideally they would get pulled from the group.
