### ISSUE TITLE
Hide slider when off

### ISSUE THREAD

**Issue by malkie-hass** [Gh61/lovelace-hue-like-light-card#97]
Hey,
I was thinking if that would be an option to have.
When the light is off do not show the slider. Would look cleaner for me. Would be nice if we could add this as an option. As always greatbjob you are doing here

Malkie

**Comment by Gh61** [comment]
Hi,

I agree, this can look nice and clean when off.
I will add it the option.

**Comment by Gh61** [comment]
Actually you can get the desired effect right now with this card-mod style:

```yaml
type: custom:hue-like-light-card
entity: light.office
icon: mdi:monitor-account
offColor: '#363636'
style: |
  .state-off .brightness-slider{
    display:none;
  }
```
I plan to add some documentation section with tips for card-mod styles. I will definitely list this example here.

As this is easier and much more customizable solution for this problem, I'm still thinking if the option to do this is even needed. I guess for now it would be overkill to add the setting. If more people will request this feature I'll add it, but I hope, this is sufficient for now.
